name: Keyper Action (Deploy Apply)

on:
  push:
    branches: [main]

jobs:
  keyper-action:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./6-use-cases/6-4-deploy-keyper-via-github-action/ # modify this
    steps:
      - uses: actions/checkout@v4
      - name: Run Keyper Action (Deploy Plan)
        uses: jarrid-xyz/keyper@v0.0.4
        with:
          args: deploy apply
